/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.StateHealthDepartment;

import Business.EcoSystem;
import Business.Enterprise.StateHealthDepartment;
import Business.Network.StateNetwork;
import Business.Order.OrderItem;
import Business.Organization.FDAOrganization;
import Business.Organization.Organization;
import Business.Organization.SHDImmuneOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProviderVaccineOrderWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zakir
 */
public class ViewOrderDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrderDetailsJPanel
     */
    private final JPanel workContainer;
    private final UserAccount userAccount;
    private final StateHealthDepartment enterprise;
    private final SHDImmuneOrganization lhdOrg;
    private final EcoSystem business;
    private final StateNetwork state;
    private final ProviderVaccineOrderWorkRequest request;
    
    public ViewOrderDetailsJPanel(JPanel workContainer, UserAccount userAccount, StateHealthDepartment enterprise,SHDImmuneOrganization lhdOrg, StateNetwork state,EcoSystem business, ProviderVaccineOrderWorkRequest request) {
        initComponents();
        this.workContainer = workContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.lhdOrg = lhdOrg;
        this.business = business;
        this.state = state;
        this.request = request;
        txtOrderNumber.setText(String.valueOf(request.getVaccineOrder().getOrderNumber()));
        displayContractDetails();
        populateTable();
        
    }
    
    private void displayContractDetails(){
        
        if(request.ishalfmonthContract())
            txtContractDetails.setText("Half Monthly");
        if(request.isfullMonthContract())
            txtContractDetails.setText("Monthly");
        if(request.isasReq())
            txtContractDetails.setText("Adhoc");
        
    }
    
    private void populateTable(){
        
         int rowCount = tblDrugOrder.getRowCount();
        DefaultTableModel defaulttabelmodel = (DefaultTableModel)tblDrugOrder.getModel();
        
        for(int i=rowCount-1 ; i>=0; i--){
            defaulttabelmodel.removeRow(i);
        }
        
        for(OrderItem orderItem: request.getVaccineOrder().getItemList())
        {
            Object[] rowData = new Object[8];
            
                rowData[0] = orderItem.getVaccineDetails();
                rowData[1] = orderItem;
                rowData[2] = orderItem.getVaccineDetails().getVaccineId();
                rowData[3] = orderItem.getVaccineDetails().getBatchId();
                rowData[4] = orderItem.getVaccineDetails().getVaccinePrice();
                rowData[5] = orderItem.getQuantity();
                rowData[6] = orderItem.getVaccineDetails().getManufactureDate();
                rowData[7] = orderItem.getVaccineDetails().getVaccinePrice()*orderItem.getQuantity();
                defaulttabelmodel.addRow(rowData);

        }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblOrderNumber = new javax.swing.JLabel();
        txtOrderNumber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDrugOrder = new javax.swing.JTable();
        btnApproveOrder = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblContractDetails = new javax.swing.JLabel();
        txtContractDetails = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Order Details");

        lblOrderNumber.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblOrderNumber.setForeground(new java.awt.Color(0, 0, 102));
        lblOrderNumber.setText("Order Number:");

        txtOrderNumber.setEnabled(false);
        txtOrderNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderNumberActionPerformed(evt);
            }
        });

        tblDrugOrder.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tblDrugOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Code", "Drug Name", "Drug ID", "Lot Number", "Price", "Quantity", "Manufacture date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDrugOrder.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblDrugOrder);

        btnApproveOrder.setBackground(new java.awt.Color(0, 0, 102));
        btnApproveOrder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnApproveOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnApproveOrder.setText("Approve Order");
        btnApproveOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveOrderActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 102));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblContractDetails.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblContractDetails.setForeground(new java.awt.Color(0, 0, 102));
        lblContractDetails.setText("Contract Details:");

        txtContractDetails.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrderNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblContractDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContractDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnApproveOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderNumber)
                    .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContractDetails)
                    .addComponent(txtContractDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApproveOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnApproveOrder, lblContractDetails, lblOrderNumber, txtContractDetails, txtOrderNumber});

    }// </editor-fold>//GEN-END:initComponents

    private void txtOrderNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderNumberActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApproveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveOrderActionPerformed
        // TODO add your handling code here:
        //check if its already approved!
        if(request.getStatus().equalsIgnoreCase("LHD Approved") || request.getStatus().equalsIgnoreCase("Shipped") || request.getStatus().equalsIgnoreCase("CDC Approved") )
        {
             JOptionPane.showMessageDialog(null, "Order already approved!");
             return;
        }
        
        //fetch the cdc org and insert the request into its workQueue
        
        FDAOrganization cdcOrg = null;
        for(Organization org: business.getCdc().getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof FDAOrganization)
            {
                org.getWorkQueue().addWorkRequest(request);
            }
        }

        request.setApprovedByLHD(true);
        request.setPhdApprovedBy(userAccount);
        request.setStatus("State Health Department Approved");
        request.setreqState(state);
        
        JOptionPane.showMessageDialog(null, "Order Sent to FDA for Approval..!!");
        
    }//GEN-LAST:event_btnApproveOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveOrder;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblContractDetails;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblDrugOrder;
    private javax.swing.JTextField txtContractDetails;
    private javax.swing.JTextField txtOrderNumber;
    // End of variables declaration//GEN-END:variables
}
