/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Manufacture;

import Business.EcoSystem;
import Business.NationalEnterprise.Manufacturer;
import Business.Organization.ManufactureOrganization;
import Business.Organization.Organization;
import Business.Vaccine.Vaccine;
import Business.Vaccine.VaccineDetails;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zakir
 */
public class AddNewDrugJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewDrugJPanel
     */
    private final JPanel workContainer;
    private final Manufacturer manufacturer;
    private final EcoSystem business;
    
    public AddNewDrugJPanel(JPanel workContainer, Manufacturer manufacturer, EcoSystem business) {
        initComponents();
        this.workContainer = workContainer;
        this.manufacturer = manufacturer;
        this.business = business;
        populateDepartmentJComboBox();
        populateVaccineJComboBox();
        
        
    }
    
    private void populateDepartmentJComboBox(){
        
        comboBoxDepartmentList.removeAllItems();
        
        for(Organization org: manufacturer.getOrganizationDirectory().getOrganizationList())
            comboBoxDepartmentList.addItem(org);
        
        
    }
    
    private void populateVaccineJComboBox(){
        
        comboBoxDrugList.removeAllItems();
        
        for(Vaccine vaccine: business.getVaccineDirectory().getVaccineCatalog())
            comboBoxDrugList.addItem(vaccine);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDrugName = new javax.swing.JLabel();
        comboBoxDrugList = new javax.swing.JComboBox();
        lblLotNumber = new javax.swing.JLabel();
        txtLotNumber = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblVials = new javax.swing.JLabel();
        lblManufactureDate = new javax.swing.JLabel();
        jDateManufactureDate = new com.toedter.calendar.JDateChooser();
        btnAddDrug = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblDepartment = new javax.swing.JLabel();
        comboBoxDepartmentList = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add New Medicine");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDrugName.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblDrugName.setForeground(new java.awt.Color(0, 0, 102));
        lblDrugName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDrugName.setText("Drug Name:");

        comboBoxDrugList.setBackground(new java.awt.Color(0, 0, 102));
        comboBoxDrugList.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        comboBoxDrugList.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxDrugList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblLotNumber.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblLotNumber.setForeground(new java.awt.Color(0, 0, 102));
        lblLotNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLotNumber.setText("Lot Number:");

        txtLotNumber.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblPrice.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(0, 0, 102));
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrice.setText("Price:");

        txtPrice.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblQuantity.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(0, 0, 102));
        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQuantity.setText("Quantity:");

        txtQuantity.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblVials.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblVials.setForeground(new java.awt.Color(0, 0, 102));
        lblVials.setText("Vials");

        lblManufactureDate.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblManufactureDate.setForeground(new java.awt.Color(0, 0, 102));
        lblManufactureDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufactureDate.setText("Manufacture Date:");

        btnAddDrug.setBackground(new java.awt.Color(0, 0, 102));
        btnAddDrug.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnAddDrug.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDrug.setText("Add New Medicine");
        btnAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 102));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDepartment.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(0, 0, 102));
        lblDepartment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDepartment.setText("Department:");

        comboBoxDepartmentList.setBackground(new java.awt.Color(0, 0, 102));
        comboBoxDepartmentList.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        comboBoxDepartmentList.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxDepartmentList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 144, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLotNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtQuantity)
                                        .addGap(5, 5, 5)
                                        .addComponent(lblVials))
                                    .addComponent(txtPrice)
                                    .addComponent(txtLotNumber)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDepartment)
                                    .addComponent(lblDrugName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxDrugList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxDepartmentList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblQuantity)
                                    .addComponent(lblManufactureDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddDrug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateManufactureDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 152, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDepartment, lblDrugName, lblLotNumber, lblManufactureDate, lblPrice, lblQuantity});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(comboBoxDepartmentList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDrugList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrugName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLotNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVials))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufactureDate)
                    .addComponent(jDateManufactureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddDrug)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddDrug, comboBoxDepartmentList, comboBoxDrugList, jDateManufactureDate, lblDepartment, lblDrugName, lblLotNumber, lblManufactureDate, lblPrice, lblQuantity, lblVials, txtLotNumber, txtPrice, txtQuantity});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugActionPerformed
        // TODO add your handling code here:
        try{
        ManufactureOrganization manuOrg = (ManufactureOrganization)comboBoxDepartmentList.getSelectedItem();
        Vaccine vaccineDef = (Vaccine)comboBoxDrugList.getSelectedItem();
        String lotNumber = txtLotNumber.getText();
        if(lotNumber.trim().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Lot Number");
            return;
        }
        Double price = Double.parseDouble(txtPrice.getText());
        int quantity = Integer.parseInt(txtQuantity.getText());
        Date manufactureDate = jDateManufactureDate.getDate();
        
        
        VaccineDetails product = manuOrg.getVaccineProductCatalog().addNewVaccineProduct();
        product.setVaccineDefinition(vaccineDef);
        product.setAvailablity(quantity);
        product.setBatchId(lotNumber);
        product.setManufactureDate(manufactureDate);
        product.setAvailablity(quantity);
        product.setVaccinePrice(price);
        product.setManufacturerName(manufacturer.getName());
        
        JOptionPane.showMessageDialog(null, "Drug Added!");
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter numeric values for numeric fields");
            //return;
        }
        
        
    }//GEN-LAST:event_btnAddDrugActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrug;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboBoxDepartmentList;
    private javax.swing.JComboBox comboBoxDrugList;
    private com.toedter.calendar.JDateChooser jDateManufactureDate;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblLotNumber;
    private javax.swing.JLabel lblManufactureDate;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVials;
    private javax.swing.JTextField txtLotNumber;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
