/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Provider;

import Business.Network.StateNetwork;
import Business.Order.OrderItem;
import Business.Organization.Organization;
import Business.Organization.SHDImmuneOrganization;
import Business.WorkQueue.ProviderVaccineOrderWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zakir
 */
public class ClinicOrderDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailsOfPlacedOrderJPanel
     */
    private final JPanel workContainer;
    private final ProviderVaccineOrderWorkRequest request;
    private final StateNetwork state;
    
    public ClinicOrderDetailsJPanel(JPanel workContainer, ProviderVaccineOrderWorkRequest request, StateNetwork state) {
        initComponents();
        this.workContainer = workContainer;
        this.request = request;
        this.state = state;
        displayContractDetails();
        calculateTotalCostOfOrder();
        txtOrderNumber.setText(String.valueOf(request.getVaccineOrder().getOrderNumber()));
        populateOrderTable();
    }
    
    private void displayContractDetails(){
        
        if(request.ishalfmonthContract())
            txtOrderDetail.setText("Half Monthly");
        if(request.isfullMonthContract())
            txtOrderDetail.setText("Monthly");
        if(request.isasReq())
            txtOrderDetail.setText("Adhoc");
        
    }
    
    private void calculateTotalCostOfOrder(){
        
        double total = 0;
        for(OrderItem oi : request.getVaccineOrder().getItemList())
        {
            total = total + (oi.getVaccineDetails().getVaccinePrice()*oi.getQuantity());
        }
        txtTotalAmount.setText(String.valueOf(total));
    }
    
    private void populateOrderTable(){
        
         int rowCount = tblOrderDetails.getRowCount();
        DefaultTableModel defaulttabelmodel = (DefaultTableModel)tblOrderDetails.getModel();
        
        for(int i=rowCount-1 ; i>=0; i--){
            defaulttabelmodel.removeRow(i);
        }
        
        for(OrderItem oi: request.getVaccineOrder().getItemList())
        {
            Object[] row = new Object[9];
            
                row[0] = oi.getVaccineDetails();
                row[1] = oi;
                row[2] = oi.getVaccineDetails().getManufacturerName();
                row[3] = oi.getVaccineDetails().getVaccineId();
                row[4] = oi.getVaccineDetails().getBatchId();
                
                row[5] = oi.getVaccineDetails().getVaccinePrice();
                row[6] = oi.getQuantity();
                row[7] = oi.getVaccineDetails().getManufactureDate();
                row[8] = oi.getVaccineDetails().getVaccinePrice()*oi.getQuantity();              
                defaulttabelmodel.addRow(row);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtOrderDetail = new javax.swing.JTextField();
        lblOrderDetails = new javax.swing.JLabel();
        lblOrderCost = new javax.swing.JLabel();
        lblOrderNumber = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        txtOrderNumber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderDetails = new javax.swing.JTable();
        lblOrder = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnForwardOrderToLHD = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clinic Order Details");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtOrderDetail.setEnabled(false);

        lblOrderDetails.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblOrderDetails.setForeground(new java.awt.Color(0, 0, 102));
        lblOrderDetails.setText("Order Details:");

        lblOrderCost.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblOrderCost.setForeground(new java.awt.Color(0, 0, 102));
        lblOrderCost.setText("Total Cost of the Order:");

        lblOrderNumber.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblOrderNumber.setForeground(new java.awt.Color(0, 0, 102));
        lblOrderNumber.setText("Order Number:");

        txtTotalAmount.setEnabled(false);

        txtOrderNumber.setEnabled(false);

        tblOrderDetails.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tblOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Code", "Medicine Name", "Brand", "Medicine ID", "Batch ID", "Price", "Quantity", "Manufacture date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrderDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblOrderDetails);

        lblOrder.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblOrder.setForeground(new java.awt.Color(0, 0, 102));
        lblOrder.setText("Order");

        btnBack.setBackground(new java.awt.Color(0, 0, 102));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnForwardOrderToLHD.setBackground(new java.awt.Color(0, 0, 102));
        btnForwardOrderToLHD.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnForwardOrderToLHD.setForeground(new java.awt.Color(255, 255, 255));
        btnForwardOrderToLHD.setText("Forward the Order to SHD");
        btnForwardOrderToLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForwardOrderToLHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnForwardOrderToLHD))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrderNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblOrderCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOrderDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderDetails)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOrder)
                        .addComponent(txtOrderDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOrderCost)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOrderNumber)
                        .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOrderDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnForwardOrderToLHD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnForwardOrderToLHD, lblOrder, lblOrderCost, lblOrderDetails, lblOrderNumber, txtOrderDetail, txtOrderNumber, txtTotalAmount});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnForwardOrderToLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForwardOrderToLHDActionPerformed
        // TODO add your handling code here:
        if(request.getStatus().equalsIgnoreCase("FWD to LHD") || request.getStatus().equalsIgnoreCase("Shipped") || request.getStatus().equalsIgnoreCase("Stored"))
        {
            JOptionPane.showMessageDialog(null, "Order already forwarded to LHD!");
            return;
        }
        
        
        for(Organization org: state.getLocalHealthDepartment().getOrganizationDirectory().getOrganizationList())
                {
                    if(org instanceof SHDImmuneOrganization)
                    {
                        org.getWorkQueue().addWorkRequest(request);
                    }
                }
        request.setStatus("FWD to LHD");
        
        JOptionPane.showMessageDialog(null, "Order forwarded to LHD!");
    }//GEN-LAST:event_btnForwardOrderToLHDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnForwardOrderToLHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrderCost;
    private javax.swing.JLabel lblOrderDetails;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JTable tblOrderDetails;
    private javax.swing.JTextField txtOrderDetail;
    private javax.swing.JTextField txtOrderNumber;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
