/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Provider;

import Business.EcoSystem;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.StateNetwork;
import Business.Organization.HospitalOrganization;
import Business.UserAccount.UserAccount;
import DashboardTrial.AdminDashboard;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anzal
 */

     


public class ProviderOperationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProviderOperationWorkAreaJPanel
     */
    
    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final HospitalEnterprise enterprise;
    private final HospitalOrganization organization;
    private final EcoSystem business;
    private final StateNetwork state;
    
    public ProviderOperationWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount, HospitalEnterprise enterprise, HospitalOrganization organization, EcoSystem business, StateNetwork state) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
        this.state = state;

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        workContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mainMenu = new javax.swing.JPanel();
        btnDrugOrder = new javax.swing.JButton();
        btnManageOrder = new javax.swing.JButton();
        btnViewInventory = new javax.swing.JButton();
        btnAdministerDrug = new javax.swing.JButton();
        btnViewAdministerDrug = new javax.swing.JButton();
        btnRemoteClinicOrder = new javax.swing.JButton();
        lblProvider = new javax.swing.JLabel();
        btnViewDashboard = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 102));
        jSplitPane1.setDividerLocation(240);

        workContainer.setBackground(new java.awt.Color(102, 153, 255));
        workContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        workContainer.add(jPanel1, "card2");

        jSplitPane1.setRightComponent(workContainer);

        mainMenu.setBackground(new java.awt.Color(102, 255, 255));

        btnDrugOrder.setBackground(new java.awt.Color(0, 0, 102));
        btnDrugOrder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDrugOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnDrugOrder.setText("Place Order for Medicines");
        btnDrugOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugOrderActionPerformed(evt);
            }
        });

        btnManageOrder.setBackground(new java.awt.Color(0, 0, 102));
        btnManageOrder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrder.setText("Manage Orders");
        btnManageOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrderActionPerformed(evt);
            }
        });

        btnViewInventory.setBackground(new java.awt.Color(0, 0, 102));
        btnViewInventory.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnViewInventory.setText("View Inventory");
        btnViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInventoryActionPerformed(evt);
            }
        });

        btnAdministerDrug.setBackground(new java.awt.Color(0, 0, 102));
        btnAdministerDrug.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnAdministerDrug.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministerDrug.setText("Administer Medicine");
        btnAdministerDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministerDrugActionPerformed(evt);
            }
        });

        btnViewAdministerDrug.setBackground(new java.awt.Color(0, 0, 102));
        btnViewAdministerDrug.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnViewAdministerDrug.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAdministerDrug.setText("View Immunized Patients");
        btnViewAdministerDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAdministerDrugActionPerformed(evt);
            }
        });

        btnRemoteClinicOrder.setBackground(new java.awt.Color(0, 0, 102));
        btnRemoteClinicOrder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRemoteClinicOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoteClinicOrder.setText("Manage Remote Clinic Orders");
        btnRemoteClinicOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoteClinicOrderActionPerformed(evt);
            }
        });

        lblProvider.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        lblProvider.setForeground(new java.awt.Color(0, 0, 102));
        lblProvider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProvider.setText("PROVIDER");

        btnViewDashboard.setBackground(new java.awt.Color(0, 0, 102));
        btnViewDashboard.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnViewDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDashboard.setText("VIEW DASHBOARD");
        btnViewDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDrugOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdministerDrug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAdministerDrug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoteClinicOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProvider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblProvider)
                .addGap(84, 84, 84)
                .addComponent(btnDrugOrder)
                .addGap(18, 18, 18)
                .addComponent(btnManageOrder)
                .addGap(18, 18, 18)
                .addComponent(btnViewInventory)
                .addGap(18, 18, 18)
                .addComponent(btnAdministerDrug)
                .addGap(18, 18, 18)
                .addComponent(btnViewAdministerDrug)
                .addGap(18, 18, 18)
                .addComponent(btnRemoteClinicOrder)
                .addGap(18, 18, 18)
                .addComponent(btnViewDashboard)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(mainMenu);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoteClinicOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoteClinicOrderActionPerformed
        // TODO add your handling code here:
        ManageClinicOrdersJPanel panel = new ManageClinicOrdersJPanel(workContainer, enterprise, organization, userAccount, business, state);
        workContainer.add("ManageSatelliteOrdersJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnRemoteClinicOrderActionPerformed

    private void btnViewAdministerDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAdministerDrugActionPerformed
        // TODO add your handling code here:
        AdministeredDrugListJPanel panel = new AdministeredDrugListJPanel(workContainer, enterprise);
        workContainer.add("AdministeredVaccineListJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnViewAdministerDrugActionPerformed

    private void btnAdministerDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministerDrugActionPerformed
        // TODO add your handling code here:
        ImmunizePatientJPanel panel = new ImmunizePatientJPanel(workContainer, enterprise, organization, userAccount, business, state);
        workContainer.add("AdministerVaccineJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnAdministerDrugActionPerformed

    private void btnViewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInventoryActionPerformed
        // TODO add your handling code here:
        ViewInventoryJPanel panel = new ViewInventoryJPanel(workContainer, business, enterprise, organization);
        workContainer.add("ViewInventoryJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);

    }//GEN-LAST:event_btnViewInventoryActionPerformed

    private void btnManageOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrderActionPerformed
        // TODO add your handling code here:
        ManageOrdersJPanel panel = new ManageOrdersJPanel(workContainer, enterprise, organization, userAccount, business, state);
        workContainer.add("ManageOrdersJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageOrderActionPerformed

    private void btnDrugOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugOrderActionPerformed
        // TODO add your handling code here:
        PlaceDrugOrderJPanel panel = new PlaceDrugOrderJPanel(workContainer, enterprise, organization, userAccount, business, state);
        workContainer.add("PlaceVaccineOrderJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnDrugOrderActionPerformed

    private void btnViewDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDashboardActionPerformed
        // TODO add your handling code here:
        AdminDashboard ad = new AdminDashboard();
    }//GEN-LAST:event_btnViewDashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministerDrug;
    private javax.swing.JButton btnDrugOrder;
    private javax.swing.JButton btnManageOrder;
    private javax.swing.JButton btnRemoteClinicOrder;
    private javax.swing.JButton btnViewAdministerDrug;
    private javax.swing.JButton btnViewDashboard;
    private javax.swing.JButton btnViewInventory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblProvider;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel workContainer;
    // End of variables declaration//GEN-END:variables
}
