/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.EnterpriseAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author anzal
 */
public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final Enterprise enterprise;
    private final UserAccount userAccount;
    private final EcoSystem business;
    /**
     * Creates new form EnterpriseAdminWorkAreaJPanel
     * @param userProcessContainer
     * @param enterprise
     * @param userAccount
     * @param business
     */
    public EnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, EcoSystem business ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;  
        displayUsername();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        mainMenuContainer = new javax.swing.JPanel();
        btnManageDepartment = new javax.swing.JButton();
        btnManagePerson = new javax.swing.JButton();
        btnManageUsers = new javax.swing.JButton();
        lblEnterpriseAdmin = new javax.swing.JLabel();
        jLabelUsersname = new javax.swing.JLabel();
        workContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 102));
        jSplitPane1.setDividerLocation(180);

        mainMenuContainer.setBackground(new java.awt.Color(51, 255, 255));

        btnManageDepartment.setBackground(new java.awt.Color(0, 0, 102));
        btnManageDepartment.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageDepartment.setForeground(new java.awt.Color(255, 255, 255));
        btnManageDepartment.setText("Manage Department");
        btnManageDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDepartmentActionPerformed(evt);
            }
        });

        btnManagePerson.setBackground(new java.awt.Color(0, 0, 102));
        btnManagePerson.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManagePerson.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePerson.setText("Manage Persons");
        btnManagePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonActionPerformed(evt);
            }
        });

        btnManageUsers.setBackground(new java.awt.Color(0, 0, 102));
        btnManageUsers.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });

        lblEnterpriseAdmin.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        lblEnterpriseAdmin.setForeground(new java.awt.Color(0, 0, 102));
        lblEnterpriseAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnterpriseAdmin.setText("Enterprise Admin");

        jLabelUsersname.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabelUsersname.setForeground(new java.awt.Color(0, 0, 102));
        jLabelUsersname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsersname.setText("Username");

        javax.swing.GroupLayout mainMenuContainerLayout = new javax.swing.GroupLayout(mainMenuContainer);
        mainMenuContainer.setLayout(mainMenuContainerLayout);
        mainMenuContainerLayout.setHorizontalGroup(
            mainMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnterpriseAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManagePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUsersname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuContainerLayout.setVerticalGroup(
            mainMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuContainerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblEnterpriseAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUsersname)
                .addGap(43, 43, 43)
                .addComponent(btnManageDepartment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManagePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageUsers)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(mainMenuContainer);

        workContainer.setBackground(new java.awt.Color(204, 255, 255));
        workContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workContainer);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDepartmentActionPerformed
        // TODO add your handling code here:
        ManageDepartmentJPanel panel = new ManageDepartmentJPanel(workContainer, enterprise);
        workContainer.add("ManageDepartmentJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageDepartmentActionPerformed

    private void btnManagePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonActionPerformed
        // TODO add your handling code here:
        ManagePersonJPanel panel = new ManagePersonJPanel(workContainer, enterprise);
        workContainer.add("ManageEmployeeJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);

    }//GEN-LAST:event_btnManagePersonActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel panel = new ManageUserAccountJPanel(workContainer, enterprise, business);
        workContainer.add("ManageUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageUsersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDepartment;
    private javax.swing.JButton btnManagePerson;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JLabel jLabelUsersname;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblEnterpriseAdmin;
    private javax.swing.JPanel mainMenuContainer;
    private javax.swing.JPanel workContainer;
    // End of variables declaration//GEN-END:variables

    private void displayUsername() {
        
        String username = this.userAccount.getUsername();
        jLabelUsersname.setText(username);
        
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
