/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Distributor;

import Business.EcoSystem;
import Business.NationalEnterprise.Distributor;
import Business.Organization.DistributorOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author zakir
 */
public class DistributorEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;  
    private final Distributor enterprise;
    private final UserAccount userAccount;
    private final DistributorOrganization distributorOrg;
    private final EcoSystem business;
    /**
     * Creates new form DistributorEmployeeWorkAreaJPanel
     * @param userProcessContainer
     * @param userAccount
     * @param enterprise
     * @param distributorOrg
     * @param business
     */
    public DistributorEmployeeWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Distributor enterprise,DistributorOrganization distributorOrg,EcoSystem business ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.distributorOrg = distributorOrg;
        this.business = business;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        workContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        btnManageWareHouse = new javax.swing.JButton();
        btnManufactureShippedOrder = new javax.swing.JButton();
        btnProviderOrder = new javax.swing.JButton();
        lblDistributor = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 102));
        jSplitPane1.setDividerLocation(240);

        workContainer.setBackground(new java.awt.Color(102, 153, 255));
        workContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Distributor/dist1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        workContainer.add(jPanel1, "card2");

        jSplitPane1.setRightComponent(workContainer);

        mainMenu.setBackground(new java.awt.Color(51, 255, 255));

        btnManageWareHouse.setBackground(new java.awt.Color(0, 0, 102));
        btnManageWareHouse.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageWareHouse.setForeground(new java.awt.Color(255, 255, 255));
        btnManageWareHouse.setText("Manage Warehouse");
        btnManageWareHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageWareHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageWareHouseActionPerformed(evt);
            }
        });

        btnManufactureShippedOrder.setBackground(new java.awt.Color(0, 0, 102));
        btnManufactureShippedOrder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManufactureShippedOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnManufactureShippedOrder.setText("View Order By Manufacturer");
        btnManufactureShippedOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManufactureShippedOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufactureShippedOrderActionPerformed(evt);
            }
        });

        btnProviderOrder.setBackground(new java.awt.Color(0, 0, 102));
        btnProviderOrder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnProviderOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnProviderOrder.setText("Manage Provider Orders");
        btnProviderOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProviderOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProviderOrderActionPerformed(evt);
            }
        });

        lblDistributor.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblDistributor.setForeground(new java.awt.Color(0, 0, 102));
        lblDistributor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDistributor.setText("DISTRIBUTOR");

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProviderOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageWareHouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManufactureShippedOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDistributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblDistributor)
                .addGap(79, 79, 79)
                .addComponent(btnManageWareHouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManufactureShippedOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProviderOrder)
                .addContainerGap(808, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(mainMenu);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageWareHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWareHouseActionPerformed
        // TODO add your handling code here:
        ManageWarehouseJPanel panel = new ManageWarehouseJPanel(workContainer, enterprise, distributorOrg);
        workContainer.add("ManageWarehouseJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);

    }//GEN-LAST:event_btnManageWareHouseActionPerformed

    private void btnManufactureShippedOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufactureShippedOrderActionPerformed
        // TODO add your handling code here:
        ManageOrdersfromManufacturerJPanel panel = new ManageOrdersfromManufacturerJPanel(workContainer, enterprise, distributorOrg);
        workContainer.add("ManageOrdersfromManufacturerJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManufactureShippedOrderActionPerformed

    private void btnProviderOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProviderOrderActionPerformed
        // TODO add your handling code here:
        ManageProviderOrdersJPanel panel = new ManageProviderOrdersJPanel(workContainer, enterprise, distributorOrg, userAccount, business);
        workContainer.add("ManageProviderOrdersJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnProviderOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageWareHouse;
    private javax.swing.JButton btnManufactureShippedOrder;
    private javax.swing.JButton btnProviderOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblDistributor;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel workContainer;
    // End of variables declaration//GEN-END:variables
}
