/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Distributor;

import Business.Enterprise.Enterprise;
import Business.Organization.DistributorOrganization;
import Business.Vaccine.VaccineDetails;
import Business.Warehouse.Warehouse;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author zakir
 */
public class ManageWarehouseJPanel extends javax.swing.JPanel {

    private final JPanel workContainer;
    private final Enterprise enterprise;
    private final DistributorOrganization distributorOrganization;
    /**
     * Creates new form ManageWarehouseJPanel
     * @param workContainer
     * @param enterprise
     * @param distributorOrganization
     */
    public ManageWarehouseJPanel(JPanel workContainer,Enterprise enterprise, DistributorOrganization distributorOrganization ) {
        initComponents();
        this.workContainer = workContainer;
        this.enterprise = enterprise;
        this.distributorOrganization = distributorOrganization;
        populateTable();
    }
    
    
    private void populateTable(){
        
        DefaultTableModel defaulttabelmodel = (DefaultTableModel) tblWarehouseDetails.getModel();
        defaulttabelmodel.setRowCount(0);
        
        for(Warehouse warehouse : distributorOrganization.getWarehouseDir().getWarehouseList())
        {
            Object[] row = new Object[3];
            row[0] = warehouse;
            row[1] = warehouse.getLocation();
            row[2] = calculateTotalVaccines(warehouse);
            defaulttabelmodel.addRow(row);
        }
   
        
    }
    
    
    private int calculateTotalVaccines(Warehouse warehouse){
        
        int totalVaccines = 0;
        for(VaccineDetails product : warehouse.getVaccineInventoryList())
        {   
            totalVaccines = totalVaccines + product.getAvailablity();
            
        }
        return totalVaccines;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWarehouseDetails = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnAddWareHouse = new javax.swing.JButton();
        btnViewInventory = new javax.swing.JButton();
        btnRemoveWarehouse = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lbl1.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 102));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Manage Warehouses");
        lbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblWarehouseDetails.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tblWarehouseDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Location", "Total Vaccines"
            }
        ));
        tblWarehouseDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblWarehouseDetails);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        lbl2.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 102));
        lbl2.setText("Add New Warehouse:");

        lbl3.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 102));
        lbl3.setText("Location:");

        txtLocation.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        btnAddWareHouse.setBackground(new java.awt.Color(0, 0, 102));
        btnAddWareHouse.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnAddWareHouse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddWareHouse.setText("Add Warehouse");
        btnAddWareHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddWareHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWareHouseActionPerformed(evt);
            }
        });

        btnViewInventory.setBackground(new java.awt.Color(0, 0, 102));
        btnViewInventory.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnViewInventory.setText("View Inventory");
        btnViewInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInventoryActionPerformed(evt);
            }
        });

        btnRemoveWarehouse.setBackground(new java.awt.Color(0, 0, 102));
        btnRemoveWarehouse.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRemoveWarehouse.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveWarehouse.setText("Remove Warehouse");
        btnRemoveWarehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveWarehouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRemoveWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddWareHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtLocation)))
                            .addComponent(lbl2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewInventory)
                    .addComponent(btnRemoveWarehouse))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddWareHouse)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddWareHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWareHouseActionPerformed
        // TODO add your handling code here:

        String location = txtLocation.getText();
        Warehouse warehouse = distributorOrganization.getWarehouseDir().addNewWareHouse();
        warehouse.setLocation(location);
        populateTable();

    }//GEN-LAST:event_btnAddWareHouseActionPerformed

    private void btnViewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInventoryActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblWarehouseDetails.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Kindly select a Warehouse from table");
            return;
        }

        Warehouse warehouse = (Warehouse)tblWarehouseDetails.getValueAt(selectedRow, 0);

        ViewInventoryJPanel panel = new ViewInventoryJPanel(workContainer, warehouse);
        workContainer.add("ViewInventoryJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);

    }//GEN-LAST:event_btnViewInventoryActionPerformed

    private void btnRemoveWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveWarehouseActionPerformed
        // TODO add your handling code here:
        int row = tblWarehouseDetails.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a warehouse from the table and try again.");
            return;
        }

        //Person person = (Person)tblPersonDetails.getValueAt(row, 0);
        Warehouse warehouse = (Warehouse)tblWarehouseDetails.getValueAt(row, 0);
        
//        Organization organize = (Organization) tblPersonDetails.getValueAt(row, 4);
//        organize.getPersonDirectory().removePerson(person);
        distributorOrganization.getWarehouseDir().removeWarehouse(warehouse);
//        populatePersonTable();
        populateTable();
    }//GEN-LAST:event_btnRemoveWarehouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWareHouse;
    private javax.swing.JButton btnRemoveWarehouse;
    private javax.swing.JButton btnViewInventory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JTable tblWarehouseDetails;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
}
