/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Distributor;

import Business.Enterprise.Enterprise;
import Business.Order.OrderItem;
import Business.Organization.DistributorOrganization;
import Business.Vaccine.VaccineDetails;
import Business.Warehouse.Warehouse;
import Business.WorkQueue.VaccineOrderWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author zakir
 */
public class StoreDrugsJPanel extends javax.swing.JPanel {

    private final JPanel workContainer;
    private final Enterprise enterprise;
    private final DistributorOrganization distributorOrganization;
    private final VaccineOrderWorkRequest request;
    
    /**
     * Creates new form StoreVaccinesJPanel
     * @param workContainer
     * @param enterprise
     * @param distributorOrganization
     * @param request
     */
    public StoreDrugsJPanel(JPanel workContainer,Enterprise enterprise, DistributorOrganization distributorOrganization, VaccineOrderWorkRequest request) {
        initComponents();
        this.workContainer = workContainer;
        this.enterprise = enterprise;
        this.distributorOrganization = distributorOrganization;
        this.request = request;
        txtOrderNumber.setText(String.valueOf(request.getVaccineOrder().getOrderNumber()));
        populateTable();
        calculateTotalAmount();
        populateWarehouseComboBox();
        
    }
    
    private void populateTable() {

        DefaultTableModel defaulttabelmodel = (DefaultTableModel) tblOrderDetails.getModel();

        defaulttabelmodel.setRowCount(0);

        for (OrderItem orderItem : request.getVaccineOrder().getItemList()) {
            Object[] row = new Object[4];
            row[0] = orderItem.getVaccineDetails().getVaccineDefinition().getVaccineCode();
            row[1] = orderItem;
            row[2] = orderItem.getQuantity();
            row[3] = orderItem.getVaccineDetails().getVaccinePrice() * orderItem.getQuantity();

            defaulttabelmodel.addRow(row);
        }
    }
    
     private void calculateTotalAmount() {

        double totalAmount = 0;
        for (OrderItem orderItem : request.getVaccineOrder().getItemList()) {
            totalAmount = totalAmount + (orderItem.getVaccineDetails().getVaccinePrice() * orderItem.getQuantity());
        }

        txtTotalAmount.setText(String.valueOf(totalAmount));
    }
     
     private void populateWarehouseComboBox(){
         comboBoxWarehouseList.removeAllItems();
         
         for(Warehouse warehouse: distributorOrganization.getWarehouseDir().getWarehouseList())
         {
             comboBoxWarehouseList.addItem(warehouse);
         }
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        btnStore = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderDetails = new javax.swing.JTable();
        lbl4 = new javax.swing.JLabel();
        txtOrderNumber = new javax.swing.JTextField();
        lbl6 = new javax.swing.JLabel();
        comboBoxWarehouseList = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(204, 255, 255));

        lbl1.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 102));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Store Medicine");
        lbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl2.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 102));
        lbl2.setText("Total Amount of Order: ");

        txtTotalAmount.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtTotalAmount.setForeground(new java.awt.Color(0, 0, 102));
        txtTotalAmount.setEnabled(false);

        btnStore.setBackground(new java.awt.Color(0, 0, 102));
        btnStore.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnStore.setForeground(new java.awt.Color(255, 255, 255));
        btnStore.setText("Store Medicine");
        btnStore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 102));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbl3.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 102));
        lbl3.setText("Particulars:");

        tblOrderDetails.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tblOrderDetails.setForeground(new java.awt.Color(0, 0, 102));
        tblOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Code", "Medicine Name", "Quantity", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrderDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblOrderDetails);

        lbl4.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 102));
        lbl4.setText("Order Number:");

        txtOrderNumber.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtOrderNumber.setForeground(new java.awt.Color(0, 0, 102));
        txtOrderNumber.setEnabled(false);

        lbl6.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lbl6.setForeground(new java.awt.Color(0, 0, 102));
        lbl6.setText("Warehouse:");

        comboBoxWarehouseList.setBackground(new java.awt.Color(0, 0, 102));
        comboBoxWarehouseList.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        comboBoxWarehouseList.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxWarehouseList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(320, 320, 320))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl6)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxWarehouseList, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStore, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1)
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl6)
                    .addComponent(comboBoxWarehouseList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStore))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreActionPerformed
        // TODO add your handling code here:
        if(request.getStatus().equalsIgnoreCase("Stored")) {
            JOptionPane.showMessageDialog(null, "Order already Stored!");
            return;
        }

        int selectedRow = tblOrderDetails.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select an Item from table");
            return;
        }
        OrderItem oi = (OrderItem)tblOrderDetails.getValueAt(selectedRow, 1);

        Warehouse warehouse = (Warehouse)comboBoxWarehouseList.getSelectedItem();

        if(warehouse==null)
        {
            JOptionPane.showMessageDialog(null, "Warehouse not created");
            return;
        }

        VaccineDetails orderedVaccine = oi.getVaccineDetails();
        boolean flag = false;
        for(VaccineDetails product: warehouse.getVaccineInventoryList())
        {
            if(orderedVaccine.getBatchId().equals(product.getBatchId()) && orderedVaccine.getVaccineDefinition().getVaccineName().equals(product.getVaccineDefinition().getVaccineName()) && orderedVaccine.getManufacturerName().equalsIgnoreCase(product.getManufacturerName()))
            {   flag = true;
                product.setAvailablity(product.getAvailablity()+oi.getQuantity());
                break;

            }

        }

        if(flag == false)
        {
            VaccineDetails prod = warehouse.addNewVaccineProduct();
            prod.setAvailablity(oi.getQuantity());
            prod.setBatchId(oi.getVaccineDetails().getBatchId());
            prod.setManufactureDate(oi.getVaccineDetails().getManufactureDate());
            prod.setManufacturerName(oi.getVaccineDetails().getManufacturerName());
            prod.setVaccineDefinition(oi.getVaccineDetails().getVaccineDefinition());
            prod.setVaccineId(oi.getVaccineDetails().getVaccineId());
            prod.setVaccinePrice(oi.getVaccineDetails().getVaccinePrice());

        }

        request.setStatus("Stored");

        JOptionPane.showMessageDialog(null, "Vaccine Stored in the Warehouse!");

    }//GEN-LAST:event_btnStoreActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnStore;
    private javax.swing.JComboBox comboBoxWarehouseList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl6;
    private javax.swing.JTable tblOrderDetails;
    private javax.swing.JTextField txtOrderNumber;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
