
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.NationalEnterprise.Manufacturer;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanal
 */
public class ManageManufacturerDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageManufacturerDetailsJPanel
     */
     private final JPanel workContainer;
    private final EcoSystem business;
    
    public ManageManufacturerDetailsJPanel(JPanel workContainer, EcoSystem business) {
        initComponents();
        this.workContainer = workContainer;
        this.business = business;
        populateTable();
        
    }
    
    private void populateTable(){
        int rowCount = tblManufacturerDetails.getRowCount();
         DefaultTableModel defaulttabelmodel = (DefaultTableModel)tblManufacturerDetails.getModel();
        
        //delete rows
        for(int i=rowCount-1 ; i>=0; i--){
            defaulttabelmodel.removeRow(i);
        }
        
        //populate the table
        for (Manufacturer manufacturer: business.getManufacturerDirectory().getManufacturerDirectory()){
            Object[] row = new Object[1];
            row[0]=manufacturer;
            
            defaulttabelmodel.addRow(row);
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManufacturerDetails = new javax.swing.JTable();
        btnCreateAdmin = new javax.swing.JButton();
        btnRemoveManufacturer = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblManufacturerName = new javax.swing.JLabel();
        txtManufacturerName = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Manufacturers");

        tblManufacturerDetails.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tblManufacturerDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblManufacturerDetails.setColumnSelectionAllowed(true);
        tblManufacturerDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblManufacturerDetails);
        tblManufacturerDetails.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnCreateAdmin.setBackground(new java.awt.Color(0, 51, 153));
        btnCreateAdmin.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnCreateAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAdmin.setText("Create Admin");
        btnCreateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminActionPerformed(evt);
            }
        });

        btnRemoveManufacturer.setBackground(new java.awt.Color(0, 51, 153));
        btnRemoveManufacturer.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnRemoveManufacturer.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveManufacturer.setText("Remove");
        btnRemoveManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveManufacturerActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        lblManufacturerName.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        lblManufacturerName.setForeground(new java.awt.Color(0, 0, 102));
        lblManufacturerName.setText("Manufacturer Name: ");

        btnadd.setBackground(new java.awt.Color(0, 51, 153));
        btnadd.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add Manufacturer");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblManufacturerName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtManufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnadd)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRemoveManufacturer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCreateAdmin)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateAdmin)
                    .addComponent(btnRemoveManufacturer))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturerName)
                    .addComponent(txtManufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnadd, lblManufacturerName, txtManufacturerName});

    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[a-zA-Z]+$");
        String name = txtManufacturerName.getText();
        if(name.trim().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter a Manufacturer name!");
            return;
        }
        if (!(pattern.matcher(name.trim()).matches())) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Manufacturer name");
            return;
        } 
        
        for(Manufacturer man: business.getManufacturerDirectory().getManufacturerDirectory())
        {
            if(man.getName().equalsIgnoreCase(name))
            {
                JOptionPane.showMessageDialog(null, "Manufacturer exists!");
            return;
            }
        }
        
        
        business.getManufacturerDirectory().addNewManufacturer(name);
        
        populateTable();
        
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnRemoveManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveManufacturerActionPerformed
        // TODO add your handling code here:
        
        int row = tblManufacturerDetails.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a Manufacturer from table");
            return;
        }
        
        Manufacturer manufacturer =(Manufacturer) tblManufacturerDetails.getValueAt(row, 0);
        business.getManufacturerDirectory().removeManufacturer(manufacturer);
        populateTable();
        
        
    }//GEN-LAST:event_btnRemoveManufacturerActionPerformed

    private void btnCreateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminActionPerformed
        // TODO add your handling code here:
        int row = tblManufacturerDetails.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a Manufacturer from table");
            return;
        }
        
        Manufacturer manufacturer =(Manufacturer) tblManufacturerDetails.getValueAt(row, 0);
        
        ManageManufactureAdminUserAccountJPanel panel = new ManageManufactureAdminUserAccountJPanel(workContainer, manufacturer, business );
        workContainer.add("ManageManufactureAdminUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
        
        
    }//GEN-LAST:event_btnCreateAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAdmin;
    private javax.swing.JButton btnRemoveManufacturer;
    private javax.swing.JButton btnadd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblManufacturerName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblManufacturerDetails;
    private javax.swing.JTextField txtManufacturerName;
    // End of variables declaration//GEN-END:variables
}
