
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.Disease.Disease;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanal
 */
public class ManageDiseaseCatalogJPanel extends javax.swing.JPanel {

    private final JPanel workContainer;
    private final EcoSystem business;
    
    DefaultTableModel tblModel;
    /**
     * Creates new form ManageDiseaseCatalogJPanel
     * @param workContainer
     */
    public ManageDiseaseCatalogJPanel(JPanel workContainer, EcoSystem business) {
        initComponents();
        this.workContainer = workContainer;
        this.business = business;
        populateDiseaseDetailsTable();
    }
    
     private void populateDiseaseDetailsTable(){
        
        tblModel = (DefaultTableModel) tblDiseaseDetailsList.getModel();
        tblModel.setRowCount(0);
        
        for(Disease disease : business.getDiseaseDirectory().getdiseaseDirectory())
        {
            Object[] rowData = new Object[3];
            rowData[0] = disease;
            rowData[1] = disease.getDiseaseName();
            rowData[2] = disease.getLastUpdatedTime();
            
            tblModel.addRow(rowData);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiseaseDetailsList = new javax.swing.JTable();
        btnAddDisease = new javax.swing.JButton();
        btnRemoveDisease = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Disease Catalog");

        tblDiseaseDetailsList.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tblDiseaseDetailsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Disease Name", "Last Updated on"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDiseaseDetailsList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDiseaseDetailsList);

        btnAddDisease.setBackground(new java.awt.Color(0, 51, 153));
        btnAddDisease.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnAddDisease.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDisease.setText("Add Disease");
        btnAddDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiseaseActionPerformed(evt);
            }
        });

        btnRemoveDisease.setBackground(new java.awt.Color(0, 51, 153));
        btnRemoveDisease.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnRemoveDisease.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveDisease.setText("Remove");
        btnRemoveDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDiseaseActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 51, 153));
        btnRefresh.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(btnRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRemoveDisease)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddDisease)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDisease)
                    .addComponent(btnRemoveDisease))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiseaseActionPerformed
        // TODO add your handling code here:

        AddNewDiseaseInfoJPanel diseasePanel = new AddNewDiseaseInfoJPanel(workContainer, business);
        workContainer.add("AddNewDiseaseInfoJPanel", diseasePanel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnAddDiseaseActionPerformed

    private void btnRemoveDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDiseaseActionPerformed
        // TODO add your handling code here:

        int row = tblDiseaseDetailsList.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a Disease from table");
            return;
        }

        Disease disease = (Disease)tblDiseaseDetailsList.getValueAt(row, 0);
        business.getDiseaseDirectory().removeDisease(disease);
        populateDiseaseDetailsTable();
    }//GEN-LAST:event_btnRemoveDiseaseActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateDiseaseDetailsTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDisease;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveDisease;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblDiseaseDetailsList;
    // End of variables declaration//GEN-END:variables
}
